name: intermediate_first_submission
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  http: ^1.6.0
  shared_preferences: ^2.5.3
  build_runner: ^2.10.4
  envied: ^1.3.2
  envied_generator: ^1.3.2
  get_it: ^9.1.1
  go_router: ^17.0.0
  timeago: ^3.7.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
